version: '3.3'
services:
  mysql_db_container:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: db
    restart: always
    ports:
      - 3306:3306
    volumes:
      - mysql_db_data_container:/var/lib/mysql
  adminer_container:
    image: adminer:latest
    environment:
      ADMINER_DEFAULT_SERVER: mysql_db_container
    ports:
      - 8080:8080

volumes:
  mysql_db_data_container:

  frontend:
    container_name: frontend
    build: ./frontend
    image: python-frontend:latest
    ports:
    - target: 5000
      published: 5000
      protocol: tcp
  backend:
    container_name: backend
    build: ./backend
    image: python-backend:latest
    ports:
    - target: 5003
      published: 5003
  service1:
    container_name: service1
    build: ./service1
    image: python-service1:latest
    ports:
    - target: 5001
      published: 5001
  service2:
    container_name: service2
    build: ./service2
    image: python-service2:latest
    ports:
    - target: 5002
      published: 5002

